query SEARCH_ITEMS_QUERY($searchTerm: String!) {
  items(where: {
    OR: [
      {title_contains: $searchTerm},
      {description_contains: $searchTerm},
    ]
  }) {
    id
    image
    title
  }
}
